config/routes.rb
Rails.application.routes.draw do

  root "pages#index"

  get "/auth/github", as: :github_login
  get "/auth/github/callback", to: "sessions#create"
  delete "/logout", to: "sessions#destroy", as: :logout

  get "/contributions", to: "contributions#show", as: :contributions

end

app/models/user.rb
class User < ActiveRecord::Base

  def initialize
    @service = GithubService.new
  end

  def self.service
    
  end

  def self.from_omniauth(auth_info)
    where(uid: auth_info[:uid]).first_or_create do |new_user|
      new_user.uid             = auth_info.uid
      new_user.name            = auth_info.extra.raw_info.name
      new_user.screen_name     = auth_info.extra.raw_info.login
      new_user.email           = auth_info.extra.raw_info.email
      new_user.oauth_token     = auth_info.credentials.token
      # byebug
      new_user.profile_pic_url  = auth_info.extra.raw_info.avatar_url
    end
  end

  def count(selector)
    @service = GithubService.new

    @service.count(self, selector)
  end

  def contributions
    @service.contributions(self)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

end

app/controllers/contributions_controller.rb
class ContributionsController < ApplicationController

  def show

  end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController

  def index

  end

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    # render text: request.env["omniauth.auth"].inspect
    # byebug
    if user = User.from_omniauth(request.env["omniauth.auth"])
      session[:user_id] = user.id
    end
    redirect_to root_path
  end

  def destroy
    session.clear
    redirect_to root_path
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <a class="navbar-brand" href="/">Git Consumer!</a>
    </div>
    <ul class="nav navbar-nav navbar-right">
        <% if current_user  %>
          <li><%= "Hello, #{current_user.name}" %></li>
          <li><%= link_to "Logout", logout_path, method: :delete %></li>
        <% else %>
          <li><%= link_to "Login", github_login_path %></li>
        <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GitConsumer</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= render "layouts/navbar" %>
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
INDEX TEST

<br />

<% if current_user %>
  Current_user oauth token = <%= "#{current_user.oauth_token}" %>
  <h1><%= "#{current_user.name}" %></h1>
  <h3>Number of starred repos: <%= current_user.count(:starred) %></h3>
  <h3>Followers: <%= current_user.count(:followers) %></h3>
  <h3>Following: <%= current_user.count(:following) %></h3>

  <img src="<%= current_user.profile_pic_url %>">
  <br />
  <br />

  <%= link_to  %>
<% end %>